// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: internal/proto/gokeeper.proto

package proto

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SecretKind int32

const (
	SecretKind_SECRET_UNSPECIFIED SecretKind = 0
	SecretKind_SECRET_CREDENTIALS SecretKind = 1
	SecretKind_SECRET_TEXT        SecretKind = 2
	SecretKind_SECRET_BLOB        SecretKind = 3
	SecretKind_SECRET_CREDIT_CARD SecretKind = 4
)

// Enum value maps for SecretKind.
var (
	SecretKind_name = map[int32]string{
		0: "SECRET_UNSPECIFIED",
		1: "SECRET_CREDENTIALS",
		2: "SECRET_TEXT",
		3: "SECRET_BLOB",
		4: "SECRET_CREDIT_CARD",
	}
	SecretKind_value = map[string]int32{
		"SECRET_UNSPECIFIED": 0,
		"SECRET_CREDENTIALS": 1,
		"SECRET_TEXT":        2,
		"SECRET_BLOB":        3,
		"SECRET_CREDIT_CARD": 4,
	}
)

func (x SecretKind) Enum() *SecretKind {
	p := new(SecretKind)
	*p = x
	return p
}

func (x SecretKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SecretKind) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_gokeeper_proto_enumTypes[0].Descriptor()
}

func (SecretKind) Type() protoreflect.EnumType {
	return &file_internal_proto_gokeeper_proto_enumTypes[0]
}

func (x SecretKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SecretKind.Descriptor instead.
func (SecretKind) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_gokeeper_proto_rawDescGZIP(), []int{0}
}

type Credentials struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *Credentials) Reset() {
	*x = Credentials{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_gokeeper_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Credentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credentials) ProtoMessage() {}

func (x *Credentials) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gokeeper_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Credentials.ProtoReflect.Descriptor instead.
func (*Credentials) Descriptor() ([]byte, []int) {
	return file_internal_proto_gokeeper_proto_rawDescGZIP(), []int{0}
}

func (x *Credentials) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Credentials) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type Text struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *Text) Reset() {
	*x = Text{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_gokeeper_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Text) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Text) ProtoMessage() {}

func (x *Text) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gokeeper_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Text.ProtoReflect.Descriptor instead.
func (*Text) Descriptor() ([]byte, []int) {
	return file_internal_proto_gokeeper_proto_rawDescGZIP(), []int{1}
}

func (x *Text) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type BLOB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Blob []byte `protobuf:"bytes,1,opt,name=blob,proto3" json:"blob,omitempty"`
}

func (x *BLOB) Reset() {
	*x = BLOB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_gokeeper_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BLOB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BLOB) ProtoMessage() {}

func (x *BLOB) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gokeeper_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BLOB.ProtoReflect.Descriptor instead.
func (*BLOB) Descriptor() ([]byte, []int) {
	return file_internal_proto_gokeeper_proto_rawDescGZIP(), []int{2}
}

func (x *BLOB) GetBlob() []byte {
	if x != nil {
		return x.Blob
	}
	return nil
}

type CreditCard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number string `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Year   int32  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	Month  int32  `protobuf:"varint,3,opt,name=month,proto3" json:"month,omitempty"`
	Cvv    int32  `protobuf:"varint,4,opt,name=cvv,proto3" json:"cvv,omitempty"`
	Owner  string `protobuf:"bytes,5,opt,name=owner,proto3" json:"owner,omitempty"`
}

func (x *CreditCard) Reset() {
	*x = CreditCard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_gokeeper_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreditCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreditCard) ProtoMessage() {}

func (x *CreditCard) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gokeeper_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreditCard.ProtoReflect.Descriptor instead.
func (*CreditCard) Descriptor() ([]byte, []int) {
	return file_internal_proto_gokeeper_proto_rawDescGZIP(), []int{3}
}

func (x *CreditCard) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *CreditCard) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *CreditCard) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *CreditCard) GetCvv() int32 {
	if x != nil {
		return x.Cvv
	}
	return 0
}

func (x *CreditCard) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

type Meta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *Meta) Reset() {
	*x = Meta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_gokeeper_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Meta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meta) ProtoMessage() {}

func (x *Meta) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gokeeper_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meta.ProtoReflect.Descriptor instead.
func (*Meta) Descriptor() ([]byte, []int) {
	return file_internal_proto_gokeeper_proto_rawDescGZIP(), []int{4}
}

func (x *Meta) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type StoreMetaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Meta     *Meta `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	SecretId int64 `protobuf:"varint,2,opt,name=secret_id,json=secretId,proto3" json:"secret_id,omitempty"`
}

func (x *StoreMetaRequest) Reset() {
	*x = StoreMetaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_gokeeper_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreMetaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreMetaRequest) ProtoMessage() {}

func (x *StoreMetaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gokeeper_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreMetaRequest.ProtoReflect.Descriptor instead.
func (*StoreMetaRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_gokeeper_proto_rawDescGZIP(), []int{5}
}

func (x *StoreMetaRequest) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *StoreMetaRequest) GetSecretId() int64 {
	if x != nil {
		return x.SecretId
	}
	return 0
}

type Secret struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte     `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Kind SecretKind `protobuf:"varint,2,opt,name=kind,proto3,enum=gokeeper.SecretKind" json:"kind,omitempty"`
}

func (x *Secret) Reset() {
	*x = Secret{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_gokeeper_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Secret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Secret) ProtoMessage() {}

func (x *Secret) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gokeeper_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Secret.ProtoReflect.Descriptor instead.
func (*Secret) Descriptor() ([]byte, []int) {
	return file_internal_proto_gokeeper_proto_rawDescGZIP(), []int{6}
}

func (x *Secret) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Secret) GetKind() SecretKind {
	if x != nil {
		return x.Kind
	}
	return SecretKind_SECRET_UNSPECIFIED
}

type ClientMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Meta *Meta `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Id   int64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ClientMeta) Reset() {
	*x = ClientMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_gokeeper_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMeta) ProtoMessage() {}

func (x *ClientMeta) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gokeeper_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMeta.ProtoReflect.Descriptor instead.
func (*ClientMeta) Descriptor() ([]byte, []int) {
	return file_internal_proto_gokeeper_proto_rawDescGZIP(), []int{7}
}

func (x *ClientMeta) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ClientMeta) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ClientSecret struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Secret *Secret       `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	Meta   []*ClientMeta `protobuf:"bytes,2,rep,name=meta,proto3" json:"meta,omitempty"`
	Id     int64         `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ClientSecret) Reset() {
	*x = ClientSecret{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_gokeeper_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientSecret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientSecret) ProtoMessage() {}

func (x *ClientSecret) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gokeeper_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientSecret.ProtoReflect.Descriptor instead.
func (*ClientSecret) Descriptor() ([]byte, []int) {
	return file_internal_proto_gokeeper_proto_rawDescGZIP(), []int{8}
}

func (x *ClientSecret) GetSecret() *Secret {
	if x != nil {
		return x.Secret
	}
	return nil
}

func (x *ClientSecret) GetMeta() []*ClientMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ClientSecret) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ClientSecrets struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Secrets []*ClientSecret `protobuf:"bytes,1,rep,name=secrets,proto3" json:"secrets,omitempty"`
}

func (x *ClientSecrets) Reset() {
	*x = ClientSecrets{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_gokeeper_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientSecrets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientSecrets) ProtoMessage() {}

func (x *ClientSecrets) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gokeeper_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientSecrets.ProtoReflect.Descriptor instead.
func (*ClientSecrets) Descriptor() ([]byte, []int) {
	return file_internal_proto_gokeeper_proto_rawDescGZIP(), []int{9}
}

func (x *ClientSecrets) GetSecrets() []*ClientSecret {
	if x != nil {
		return x.Secrets
	}
	return nil
}

type JWT struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *JWT) Reset() {
	*x = JWT{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_gokeeper_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JWT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JWT) ProtoMessage() {}

func (x *JWT) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gokeeper_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JWT.ProtoReflect.Descriptor instead.
func (*JWT) Descriptor() ([]byte, []int) {
	return file_internal_proto_gokeeper_proto_rawDescGZIP(), []int{10}
}

func (x *JWT) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_internal_proto_gokeeper_proto protoreflect.FileDescriptor

var file_internal_proto_gokeeper_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x67, 0x6f, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x08, 0x67, 0x6f, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x45, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x61, 0x6c, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x1a, 0x0a,
	0x04, 0x54, 0x65, 0x78, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x1a, 0x0a, 0x04, 0x42, 0x4c, 0x4f,
	0x42, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6c, 0x6f, 0x62, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x62, 0x6c, 0x6f, 0x62, 0x22, 0x76, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x43,
	0x61, 0x72, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x79,
	0x65, 0x61, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x79, 0x65, 0x61, 0x72, 0x12,
	0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x76, 0x76, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x03, 0x63, 0x76, 0x76, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x22, 0x1a, 0x0a,
	0x04, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x53, 0x0a, 0x10, 0x53, 0x74, 0x6f,
	0x72, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a,
	0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x67, 0x6f,
	0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x04, 0x6d, 0x65, 0x74,
	0x61, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x49, 0x64, 0x22, 0x46,
	0x0a, 0x06, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x28, 0x0a, 0x04,
	0x6b, 0x69, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6b,
	0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x4b, 0x69, 0x6e, 0x64,
	0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x22, 0x40, 0x0a, 0x0a, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x4d, 0x65, 0x74, 0x61, 0x12, 0x22, 0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x67, 0x6f, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x4d, 0x65,
	0x74, 0x61, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x72, 0x0a, 0x0c, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x28, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x72,
	0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67, 0x6f, 0x6b, 0x65, 0x65,
	0x70, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x52, 0x06, 0x73, 0x65, 0x63, 0x72,
	0x65, 0x74, 0x12, 0x28, 0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x41, 0x0a, 0x0d,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x73, 0x12, 0x30, 0x0a,
	0x07, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x67, 0x6f, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x52, 0x07, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x73, 0x22,
	0x1b, 0x0a, 0x03, 0x4a, 0x57, 0x54, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2a, 0x76, 0x0a, 0x0a,
	0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x16, 0x0a, 0x12, 0x53, 0x45,
	0x43, 0x52, 0x45, 0x54, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x53, 0x45, 0x43, 0x52, 0x45, 0x54, 0x5f, 0x43, 0x52, 0x45,
	0x44, 0x45, 0x4e, 0x54, 0x49, 0x41, 0x4c, 0x53, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x45,
	0x43, 0x52, 0x45, 0x54, 0x5f, 0x54, 0x45, 0x58, 0x54, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x53,
	0x45, 0x43, 0x52, 0x45, 0x54, 0x5f, 0x42, 0x4c, 0x4f, 0x42, 0x10, 0x03, 0x12, 0x16, 0x0a, 0x12,
	0x53, 0x45, 0x43, 0x52, 0x45, 0x54, 0x5f, 0x43, 0x52, 0x45, 0x44, 0x49, 0x54, 0x5f, 0x43, 0x41,
	0x52, 0x44, 0x10, 0x04, 0x32, 0x66, 0x0a, 0x04, 0x41, 0x75, 0x74, 0x68, 0x12, 0x2e, 0x0a, 0x06,
	0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x12, 0x15, 0x2e, 0x67, 0x6f, 0x6b, 0x65, 0x65, 0x70, 0x65,
	0x72, 0x2e, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x1a, 0x0d, 0x2e,
	0x67, 0x6f, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x4a, 0x57, 0x54, 0x12, 0x2e, 0x0a, 0x06,
	0x53, 0x69, 0x67, 0x6e, 0x55, 0x70, 0x12, 0x15, 0x2e, 0x67, 0x6f, 0x6b, 0x65, 0x65, 0x70, 0x65,
	0x72, 0x2e, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x1a, 0x0d, 0x2e,
	0x67, 0x6f, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x4a, 0x57, 0x54, 0x32, 0xb7, 0x03, 0x0a,
	0x06, 0x4b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x12, 0x37, 0x0a, 0x0b, 0x53, 0x74, 0x6f, 0x72, 0x65,
	0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x10, 0x2e, 0x67, 0x6f, 0x6b, 0x65, 0x65, 0x70, 0x65,
	0x72, 0x2e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6b, 0x65, 0x65,
	0x70, 0x65, 0x72, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x12, 0x3e, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x12, 0x3e, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x12, 0x3d, 0x0a, 0x09, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x1a, 0x2e,
	0x67, 0x6f, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x4d, 0x65,
	0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x67, 0x6f, 0x6b, 0x65,
	0x65, 0x70, 0x65, 0x72, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x12,
	0x3a, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x14, 0x2e,
	0x67, 0x6f, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d,
	0x65, 0x74, 0x61, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x3a, 0x0a, 0x0a, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x14, 0x2e, 0x67, 0x6f, 0x6b, 0x65,
	0x65, 0x70, 0x65, 0x72, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x1a,
	0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x3d, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x53, 0x65,
	0x63, 0x72, 0x65, 0x74, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x17, 0x2e,
	0x67, 0x6f, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53,
	0x65, 0x63, 0x72, 0x65, 0x74, 0x73, 0x42, 0x19, 0x5a, 0x17, 0x67, 0x6f, 0x6b, 0x65, 0x65, 0x70,
	0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_proto_gokeeper_proto_rawDescOnce sync.Once
	file_internal_proto_gokeeper_proto_rawDescData = file_internal_proto_gokeeper_proto_rawDesc
)

func file_internal_proto_gokeeper_proto_rawDescGZIP() []byte {
	file_internal_proto_gokeeper_proto_rawDescOnce.Do(func() {
		file_internal_proto_gokeeper_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_proto_gokeeper_proto_rawDescData)
	})
	return file_internal_proto_gokeeper_proto_rawDescData
}

var file_internal_proto_gokeeper_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_proto_gokeeper_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_internal_proto_gokeeper_proto_goTypes = []interface{}{
	(SecretKind)(0),          // 0: gokeeper.SecretKind
	(*Credentials)(nil),      // 1: gokeeper.Credentials
	(*Text)(nil),             // 2: gokeeper.Text
	(*BLOB)(nil),             // 3: gokeeper.BLOB
	(*CreditCard)(nil),       // 4: gokeeper.CreditCard
	(*Meta)(nil),             // 5: gokeeper.Meta
	(*StoreMetaRequest)(nil), // 6: gokeeper.StoreMetaRequest
	(*Secret)(nil),           // 7: gokeeper.Secret
	(*ClientMeta)(nil),       // 8: gokeeper.ClientMeta
	(*ClientSecret)(nil),     // 9: gokeeper.ClientSecret
	(*ClientSecrets)(nil),    // 10: gokeeper.ClientSecrets
	(*JWT)(nil),              // 11: gokeeper.JWT
	(*empty.Empty)(nil),      // 12: google.protobuf.Empty
}
var file_internal_proto_gokeeper_proto_depIdxs = []int32{
	5,  // 0: gokeeper.StoreMetaRequest.meta:type_name -> gokeeper.Meta
	0,  // 1: gokeeper.Secret.kind:type_name -> gokeeper.SecretKind
	5,  // 2: gokeeper.ClientMeta.meta:type_name -> gokeeper.Meta
	7,  // 3: gokeeper.ClientSecret.secret:type_name -> gokeeper.Secret
	8,  // 4: gokeeper.ClientSecret.meta:type_name -> gokeeper.ClientMeta
	9,  // 5: gokeeper.ClientSecrets.secrets:type_name -> gokeeper.ClientSecret
	1,  // 6: gokeeper.Auth.SignIn:input_type -> gokeeper.Credentials
	1,  // 7: gokeeper.Auth.SignUp:input_type -> gokeeper.Credentials
	7,  // 8: gokeeper.Keeper.StoreSecret:input_type -> gokeeper.Secret
	9,  // 9: gokeeper.Keeper.UpdateSecret:input_type -> gokeeper.ClientSecret
	9,  // 10: gokeeper.Keeper.DeleteSecret:input_type -> gokeeper.ClientSecret
	6,  // 11: gokeeper.Keeper.StoreMeta:input_type -> gokeeper.StoreMetaRequest
	8,  // 12: gokeeper.Keeper.UpdateMeta:input_type -> gokeeper.ClientMeta
	8,  // 13: gokeeper.Keeper.DeleteMeta:input_type -> gokeeper.ClientMeta
	12, // 14: gokeeper.Keeper.GetSecrets:input_type -> google.protobuf.Empty
	11, // 15: gokeeper.Auth.SignIn:output_type -> gokeeper.JWT
	11, // 16: gokeeper.Auth.SignUp:output_type -> gokeeper.JWT
	9,  // 17: gokeeper.Keeper.StoreSecret:output_type -> gokeeper.ClientSecret
	12, // 18: gokeeper.Keeper.UpdateSecret:output_type -> google.protobuf.Empty
	12, // 19: gokeeper.Keeper.DeleteSecret:output_type -> google.protobuf.Empty
	8,  // 20: gokeeper.Keeper.StoreMeta:output_type -> gokeeper.ClientMeta
	12, // 21: gokeeper.Keeper.UpdateMeta:output_type -> google.protobuf.Empty
	12, // 22: gokeeper.Keeper.DeleteMeta:output_type -> google.protobuf.Empty
	10, // 23: gokeeper.Keeper.GetSecrets:output_type -> gokeeper.ClientSecrets
	15, // [15:24] is the sub-list for method output_type
	6,  // [6:15] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_internal_proto_gokeeper_proto_init() }
func file_internal_proto_gokeeper_proto_init() {
	if File_internal_proto_gokeeper_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_proto_gokeeper_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Credentials); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_gokeeper_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Text); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_gokeeper_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BLOB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_gokeeper_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreditCard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_gokeeper_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Meta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_gokeeper_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreMetaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_gokeeper_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Secret); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_gokeeper_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_gokeeper_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientSecret); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_gokeeper_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientSecrets); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_gokeeper_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JWT); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_proto_gokeeper_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_internal_proto_gokeeper_proto_goTypes,
		DependencyIndexes: file_internal_proto_gokeeper_proto_depIdxs,
		EnumInfos:         file_internal_proto_gokeeper_proto_enumTypes,
		MessageInfos:      file_internal_proto_gokeeper_proto_msgTypes,
	}.Build()
	File_internal_proto_gokeeper_proto = out.File
	file_internal_proto_gokeeper_proto_rawDesc = nil
	file_internal_proto_gokeeper_proto_goTypes = nil
	file_internal_proto_gokeeper_proto_depIdxs = nil
}
